[package]
name = "sqids"
description = "Generate YouTube-like ids from numbers."
repository = "https://github.com/sqids/sqids-rust"
documentation = "https://docs.rs/sqids"
homepage = "https://sqids.org/rust"
version = "0.3.0"
license = "MIT"
edition = "2021"
readme = "README.md"
keywords = ["ids", "encode", "short", "sqids", "hashids"]

[dependencies]
serde = "1.0.188"
serde_json = "1.0.107"
thiserror = "1.0.49"
